apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: portfolio
          image: ghcr.io/origa2001/portfolio:4e6fc37d182d03dc3f2a327df23e9b4697d09708
          ports:
            - containerPort: 80
